const Data  = [
    {
        id: 1,
        imgSrc: '',
        destTitle: 'COPENHAGEN, DENMARK',
        route: 'Cairo - Denmark',
        departure: '30/Sep/2023',
        return: '7/Oct/2023',
        fees: '€700',
    },
    {
        id: 2,
        imgSrc: '',
        destTitle: 'PORTO, PORTUGAL',
        route: 'Greece - Portugal',
        departure: '5/Oct/2023',
        return: '20/Oct/2023',
        fees: '€500',

    },
    {
        id: 3,
        imgSrc: '',
        destTitle: 'BRUSSELS, BELGIUM',
        route: 'Portugal - Belgium',
        departure: '27/Sep/2023',
        return: '10/Oct/2023',
        fees: '€300',
    },
    {
        id: 4,
        imgSrc: '',
        destTitle: ' SAN SEBASTIAN, SPAIN',
        route: 'France - Spain',
        departure: '25/Oct/2023',
        return: '5/Nov/2023',
        fees: '€350',
    },
    {
        id: 5,
        imgSrc: '',
        destTitle: 'SAINTE-MAXIME, FRANCE',
        route: 'Greece - France',
        departure: '2/Nov/2023',
        return: '16/Nov/2023',
        fees: '€550',
    },
    {
        id: 6,
        imgSrc: '',
        destTitle: 'AMSTERDAM, NETHERLANDS',
        route: 'Italy - Netherlands',
        departure: '30/Sep/2023',
        return: '13/Oct/2023',
        fees: '€650',
    },
    {
        id: 7,
        imgSrc: '',
        destTitle: 'POZNAN, POLAND',
        route: 'Georgia - Poland',
        departure: '1/Nov/2023',
        return: '15/Nov/2023',
        fees: '€450',
    },
    {
        id: 8,
        imgSrc: '',
        destTitle: 'COPENHAGEN, DENMARK',
        route: 'Albania - Denmark',
        departure: '20/Oct/2023',
        return: '27/Oct/2023',
        fees: '€800',
    },
    {
        id: 9,
        imgSrc: '',
        destTitle: 'MALAGA, SPAIN',
        route: 'Germany - Spain',
        departure: '23/Sep/2023',
        return: '30/Sep/2023',
        fees: '€700',
    },

];